export const trainingWeeks = [
  [
    {
      id: 'wt-1',
      effort: 1,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-1',
      effort: 2,
      content: 'Recovery run',
      mileage: '3 mi',
    },
    {
      id: 'wt-2',
      effort: 3,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-2',
      effort: 2,
      content: 'Recovery run',
      mileage: '4 mi',
    },
    {
      id: 'es-1',
      effort: 4,
      content: 'Easy Run',
      mileage: '6 mi',
    },
    {
      id: 'es-2',
      effort: 2,
      content: 'Long run',
      mileage: '10 mi',
    },
    {
      id: 'of-1',
      effort: 0,
      content: 'Off',
      mileage: '0 mi',
    },
  ],
  [
    {
      id: 'wt-1',
      effort: 6,
      content: 'Hard workout',
      mileage: '11 mi',
    },
    {
      id: 'rt-1',
      effort: 2,
      content: 'Recovery run',
      mileage: '2 mi',
    },
    {
      id: 'wt-2',
      effort: 5,
      content: 'Hard workout',
      mileage: '11 mi',
    },
    {
      id: 'rt-2',
      effort: 2,
      content: 'Recovery run',
      mileage: '3 mi',
    },
    {
      id: 'es-1',
      effort: 3,
      content: 'Easy Run',
      mileage: '5 mi',
    },
    {
      id: 'es-2',
      effort: 4,
      content: 'Long run',
      mileage: '8 mi',
    },
    {
      id: 'of-1',
      effort: 0,
      content: 'Off',
      mileage: '0 mi',
    },
  ],
  [
    {
      id: 'wt-1',
      effort: 6,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-1',
      effort: 2,
      content: 'Recovery run',
      mileage: '3 mi',
    },
    {
      id: 'wt-2',
      effort: 5,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-2',
      effort: 2,
      content: 'Recovery run',
      mileage: '4 mi',
    },
    {
      id: 'es-1',
      effort: 3,
      content: 'Easy Run',
      mileage: '6 mi',
    },
    {
      id: 'es-2',
      effort: 4,
      content: 'Long run',
      mileage: '10 mi',
    },
    {
      id: 'of-1',
      effort: 0,
      content: 'Off',
      mileage: '0 mi',
    },
  ],
  [
    {
      id: 'wt-1',
      effort: 6,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-1',
      effort: 2,
      content: 'Recovery run',
      mileage: '3 mi',
    },
    {
      id: 'wt-2',
      effort: 5,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-2',
      effort: 2,
      content: 'Recovery run',
      mileage: '4 mi',
    },
    {
      id: 'es-1',
      effort: 3,
      content: 'Easy Run',
      mileage: '6 mi',
    },
    {
      id: 'es-2',
      effort: 4,
      content: 'Long run',
      mileage: '10 mi',
    },
    {
      id: 'of-1',
      effort: 0,
      content: 'Off',
      mileage: '0 mi',
    },
  ],
  [
    {
      id: 'wt-1',
      effort: 6,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-1',
      effort: 2,
      content: 'Recovery run',
      mileage: '3 mi',
    },
    {
      id: 'wt-2',
      effort: 5,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-2',
      effort: 2,
      content: 'Recovery run',
      mileage: '4 mi',
    },
    {
      id: 'es-1',
      effort: 3,
      content: 'Easy Run',
      mileage: '6 mi',
    },
    {
      id: 'es-2',
      effort: 4,
      content: 'Long run',
      mileage: '10 mi',
    },
    {
      id: 'of-1',
      effort: 0,
      content: 'Off',
      mileage: '0 mi',
    },
  ],
  [
    {
      id: 'wt-1',
      effort: 6,
      content: 'Hard workout',
      mileage: '11 mi',
    },
    {
      id: 'rt-1',
      effort: 2,
      content: 'Recovery run',
      mileage: '2 mi',
    },
    {
      id: 'wt-2',
      effort: 5,
      content: 'Hard workout',
      mileage: '11 mi',
    },
    {
      id: 'rt-2',
      effort: 2,
      content: 'Recovery run',
      mileage: '3 mi',
    },
    {
      id: 'es-1',
      effort: 3,
      content: 'Easy Run',
      mileage: '5 mi',
    },
    {
      id: 'es-2',
      effort: 4,
      content: 'Long run',
      mileage: '8 mi',
    },
    {
      id: 'of-1',
      effort: 0,
      content: 'Off',
      mileage: '0 mi',
    },
  ],
  [
    {
      id: 'wt-1',
      effort: 6,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-1',
      effort: 2,
      content: 'Recovery run',
      mileage: '3 mi',
    },
    {
      id: 'wt-2',
      effort: 5,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-2',
      effort: 2,
      content: 'Recovery run',
      mileage: '4 mi',
    },
    {
      id: 'es-1',
      effort: 3,
      content: 'Easy Run',
      mileage: '6 mi',
    },
    {
      id: 'es-2',
      effort: 4,
      content: 'Long run',
      mileage: '10 mi',
    },
    {
      id: 'of-1',
      effort: 0,
      content: 'Off',
      mileage: '0 mi',
    },
  ],
  [
    {
      id: 'wt-1',
      effort: 6,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-1',
      effort: 2,
      content: 'Recovery run',
      mileage: '3 mi',
    },
    {
      id: 'wt-2',
      effort: 5,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-2',
      effort: 2,
      content: 'Recovery run',
      mileage: '4 mi',
    },
    {
      id: 'es-1',
      effort: 3,
      content: 'Easy Run',
      mileage: '6 mi',
    },
    {
      id: 'es-2',
      effort: 4,
      content: 'Long run',
      mileage: '10 mi',
    },
    {
      id: 'of-1',
      effort: 0,
      content: 'Off',
      mileage: '0 mi',
    },
  ],
  [
    {
      id: 'wt-1',
      effort: 6,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-1',
      effort: 2,
      content: 'Recovery run',
      mileage: '3 mi',
    },
    {
      id: 'wt-2',
      effort: 5,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-2',
      effort: 2,
      content: 'Recovery run',
      mileage: '4 mi',
    },
    {
      id: 'es-1',
      effort: 3,
      content: 'Easy Run',
      mileage: '6 mi',
    },
    {
      id: 'es-2',
      effort: 4,
      content: 'Long run',
      mileage: '10 mi',
    },
    {
      id: 'of-1',
      effort: 0,
      content: 'Off',
      mileage: '0 mi',
    },
  ],
  [
    {
      id: 'wt-1',
      effort: 6,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-1',
      effort: 2,
      content: 'Recovery run',
      mileage: '3 mi',
    },
    {
      id: 'wt-2',
      effort: 5,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-2',
      effort: 2,
      content: 'Recovery run',
      mileage: '4 mi',
    },
    {
      id: 'es-1',
      effort: 3,
      content: 'Easy Run',
      mileage: '6 mi',
    },
    {
      id: 'es-2',
      effort: 4,
      content: 'Long run',
      mileage: '10 mi',
    },
    {
      id: 'of-1',
      effort: 0,
      content: 'Off',
      mileage: '0 mi',
    },
  ],
  [
    {
      id: 'wt-1',
      effort: 6,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-1',
      effort: 2,
      content: 'Recovery run',
      mileage: '3 mi',
    },
    {
      id: 'wt-2',
      effort: 5,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-2',
      effort: 2,
      content: 'Recovery run',
      mileage: '4 mi',
    },
    {
      id: 'es-1',
      effort: 3,
      content: 'Easy Run',
      mileage: '6 mi',
    },
    {
      id: 'es-2',
      effort: 4,
      content: 'Long run',
      mileage: '10 mi',
    },
    {
      id: 'of-1',
      effort: 0,
      content: 'Off',
      mileage: '0 mi',
    },
  ],
  [
    {
      id: 'wt-1',
      effort: 6,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-1',
      effort: 2,
      content: 'Recovery run',
      mileage: '3 mi',
    },
    {
      id: 'wt-2',
      effort: 5,
      content: 'Hard workout',
      mileage: '10 mi',
    },
    {
      id: 'rt-2',
      effort: 2,
      content: 'Recovery run',
      mileage: '4 mi',
    },
    {
      id: 'es-1',
      effort: 3,
      content: 'Easy Run',
      mileage: '6 mi',
    },
    {
      id: 'es-2',
      effort: 4,
      content: 'Long run',
      mileage: '10 mi',
    },
    {
      id: 'of-1',
      effort: 0,
      content: 'Off',
      mileage: '0 mi',
    },
  ],
];
