fragment AuthorSnippet on Authors_Document {
  sys {
    filename
  }
  data {
    ... on Author_Doc_Data {
      image
      name
    }
    ... on Athlete_Doc_Data {
      image
      name
    }
  }
}

fragment AuthorSnippetNav on Authors_Document {
  sys {
    filename
  }
  data {
    ... on Author_Doc_Data {
      image
      name
    }
    ... on Athlete_Doc_Data {
      image
      name
    }
  }
}

fragment BaseAuthor on Authors_Document {
  __typename
  id
  sys {
    filename
    collection {
      slug
    }
  }
  data {
    __typename
    ... on Athlete_Doc_Data {
      name
      country
      image
      social_media {
        source
        handle
      }
      personal_bests {
        event
        time
      }
      _body
    }
    ... on Author_Doc_Data {
      name
      accolades {
        figure
        description
      }
      description
      role
      image
      _body
      ebook {
        title
        description
        link
        link_text
        image
      }
    }
  }
}

fragment ThumbnailPost on Posts_Document {
  sys {
    filename
  }
  data {
    __typename
    ... on Post_Doc_Data {
      title
      tags
      image
      preface
      author {
        sys {
          filename
        }
        data {
          __typename
          ... on Athlete_Doc_Data {
            name
            image
          }
          ... on Author_Doc_Data {
            name
            image
          }
        }
      }
    }
  }
}

query Member($relativePath: String!) {
  getNavDocument(relativePath: "site-nav.md") {
    ...Nav
  }
  getAuthorsDocument(relativePath: $relativePath) {
    sys {
      filename
      collection {
        slug
      }
    }
    data {
      __typename
      ... on Athlete_Doc_Data {
        name
      }
      ... on Author_Doc_Data {
        name
        accolades {
          figure
          description
        }
        description
        role
        image
        story_image
        bio_image
        posts_collection {
          ...ThumbnailPost
        }
        form {
          data {
            ... on JenCcoaching_Doc_Data {
              title
              description
              fields {
                __typename
                ... on FieldText_Data {
                  label
                  name
                  placeholder
                  subLabel
                  prefix
                  suffix
                }
                ... on FieldBoolean_Data {
                  label
                  subLabel
                  name
                }
                ... on FieldRadio_Data {
                  label
                  subLabel
                  placeholder
                  name
                  options {
                    label
                    value
                  }
                }
                ... on FieldGroupText_Data {
                  label
                  subLabel
                  prefix_class
                  fields {
                    __typename
                    ... on FieldText_Data {
                      label
                      subLabel
                      name
                      placeholder
                      prefix
                      suffix
                    }
                  }
                }
                ... on FieldWeekCheckbox_Data {
                  label
                  subLabel
                  name
                }
                ... on FieldTextarea_Data {
                  label
                  subLabel
                  placeholder
                  name
                }
                ... on FieldCheckbox_Data {
                  label
                  subLabel
                  placeholder
                  name
                  options {
                    label
                    value
                  }
                }
              }
            }
          }
        }
        _body
        ebook {
          title
          description
          link
          link_text
          image
        }
      }
    }
  }
}

query BaseAuthorList {
  getNavDocument(relativePath: "site-nav.md") {
    ...Nav
  }
  page: getPagesDocument(relativePath: "our-team.md") {
    id
    data {
      ... on Page_Doc_Data {
        __typename
        seo {
          title
          description
          image
        }
        layers {
          __typename
          ... on CuratedCollection_Data {
            ...CuratedCollection
          }
          ... on LayerSponsors_Data {
            title
            sponsors {
              name
              link
            }
          }
          ... on LayerCta_Data {
            description
            cta_text
            cta_link
            cta_image
          }
          ... on LayerLeadership_Data {
            title
            leaders {
              ...BaseAuthor
            }
          }
          ... on LayerPostList_Data {
            description
            posts {
              data {
                ... on Post_Doc_Data {
                  title
                  tags
                  preface
                  image
                  image_small
                  author {
                    ...BaseAuthor
                  }
                }
              }
            }
          }
          ... on LayerDarkFeature_Data {
            hint
            title
            description
            feature_list {
              header
              description
            }
          }
        }
      }
    }
  }
  terrence: getAuthorsDocument(relativePath: "terrence.md") {
    ...BaseAuthor
  }
  jen: getAuthorsDocument(relativePath: "jen.md") {
    ...BaseAuthor
  }
  christian: getAuthorsDocument(relativePath: "christian.md") {
    ...BaseAuthor
  }
  chris: getAuthorsDocument(relativePath: "chris.md") {
    ...BaseAuthor
  }
  emily: getAuthorsDocument(relativePath: "emily.md") {
    ...BaseAuthor
  }
  eric: getAuthorsDocument(relativePath: "eric.md") {
    ...BaseAuthor
  }
  heidi: getAuthorsDocument(relativePath: "heidi.md") {
    ...BaseAuthor
  }
  nicole: getAuthorsDocument(relativePath: "nicole.md") {
    ...BaseAuthor
  }
  sarah: getAuthorsDocument(relativePath: "sarah.md") {
    ...BaseAuthor
  }
}
