fragment authorFragment on Authors_Document {
  __typename
  id
  sys {
    filename
    collection {
      slug
    }
  }
  data {
    __typename
    ... on Athlete_Doc_Data {
      name
      country
      image
      social_media {
        source
        handle
      }
      personal_bests {
        event
        time
      }
      _body
    }
    ... on Author_Doc_Data {
      name
      accolades {
        figure
        description
      }
      description
      role
      image
      _body
      ebook {
        title
        description
        link
        link_text
        image
      }
    }
  }
}

query AuthorList($relativePath: String = "site-nav.md") {
  getNavDocument(relativePath: $relativePath) {
    ...Nav
  }
  page: getPagesDocument(relativePath: "our-team.md") {
    id
    data {
      ... on Page_Doc_Data {
        __typename
        layers {
          __typename
          ... on LayerPostList_Data {
            description
            posts {
              data {
                ... on Post_Doc_Data {
                  title
                  tags
                  preface
                  image
                  image_small
                  author {
                    ...authorFragment
                  }
                }
              }
            }
          }
          ... on LayerDarkFeature_Data {
            hint
            title
            description
            feature_list {
              header
              description
            }
          }
        }
      }
    }
  }
  terrence: getAuthorsDocument(relativePath: "terrence.md") {
    ...authorFragment
  }
  jen: getAuthorsDocument(relativePath: "jen.md") {
    ...authorFragment
  }
  christian: getAuthorsDocument(relativePath: "christian.md") {
    ...authorFragment
  }
  chris: getAuthorsDocument(relativePath: "chris.md") {
    ...authorFragment
  }
  emily: getAuthorsDocument(relativePath: "emily.md") {
    ...authorFragment
  }
  eric: getAuthorsDocument(relativePath: "eric.md") {
    ...authorFragment
  }
  heidi: getAuthorsDocument(relativePath: "heidi.md") {
    ...authorFragment
  }
  nicole: getAuthorsDocument(relativePath: "nicole.md") {
    ...authorFragment
  }
  sarah: getAuthorsDocument(relativePath: "sarah.md") {
    ...authorFragment
  }
}
