query TrainingPlanPage {
  getNavDocument(relativePath: "site-nav.md") {
    ...Nav
  }
  getPagesDocument(relativePath: "training-page.md") {
    data {
      ... on TrainingPage_Doc_Data {
        faq {
          question
          answer
        }
        _body
      }
    }
  }
}
