query getPagesAndNavDocument($relativePath: String!) {
  getNavDocument(relativePath: "site-nav.md") {
    data {
      ...NavParts2
    }
  }
  getPagesDocument(relativePath: $relativePath) {
    id
    __typename
    data {
      __typename
      ...PagesPartsWithReferences
    }
  }
}

fragment NavParts2 on Nav {
  ... on NavNav {
    items {
      __typename
      ... on NavNavItemsNavItemPopout {
        label
        children {
          __typename
          label
          description
          value
          icon
        }
        extra {
          __typename
          label
          value
          icon
        }
      }
      ... on NavNavItemsNavItemMore {
        label
        featured_post {
          ... on Document {
            id
            sys {
              filename
              breadcrumbs
            }
          }
          ... on PostsDocument {
            data {
              ... on PostsPost {
                image
                title
                preface
                author {
                  ... on Document {
                    sys {
                      filename
                    }
                  }
                  __typename
                  ... on AuthorsDocument {
                    data {
                      __typename
                      ... on AuthorsAuthor {
                        name
                        image
                      }
                    }
                  }
                }
              }
            }
          }
        }
        from_the_blog {
          __typename
          reference {
            ... on Document {
              id
              sys {
                filename
                breadcrumbs
              }
            }
            ... on PostsDocument {
              data {
                ... on PostsPost {
                  image
                  title
                  preface
                  author {
                    ... on Document {
                      sys {
                        filename
                      }
                    }
                    __typename
                    ... on AuthorsDocument {
                      data {
                        __typename
                        ... on AuthorsAuthor {
                          name
                          image
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        read_more {
          __typename
          label
          value
        }
      }
      ... on NavNavItemsNavItemLink {
        label
        value
      }
    }
    show_auth
  }
}

fragment PagesPartsWithReferences on Pages {
  ... on PagesPage {
    title
    seo {
      __typename
      title
      description
      image
    }
    layers {
      __typename
      ... on PagesPageLayersLayerHero {
        image
      }
      ... on PagesPageLayersLayerTeam {
        description
        members {
          __typename
          reference {
            ... on AuthorsDocument {
              __typename
              id
              sys {
                filename
              }
              data {
                __typename
                ... on AuthorsAthlete {
                  name
                  image
                  country
                  personal_bests {
                    event
                    time
                  }
                  social_media {
                    source
                    handle
                  }
                }
                ... on AuthorsAuthor {
                  image
                  name
                  role
                  bioDescription
                }
              }
            }
            ... on Document {
              id
            }
          }
        }
      }
      ... on PagesPageLayersLayerPostList {
        postListDescription
        posts {
          __typename
          reference {
            ... on PostsDocument {
              __typename
              sys {
                filename
              }
              data {
                ... on PostsPost {
                  ...PostsParts
                }
              }
            }
          }
        }
      }
      ... on PagesPageLayersLayerDarkFeature {
        hint
        title
        description
        feature_list {
          __typename
          header
          description
        }
      }
      ... on PagesPageLayersLayerLeadership {
        title
        leaders {
          __typename
          reference {
            ... on AuthorsDocument {
              __typename
              sys {
                filename
              }
              data {
                ... on AuthorsAuthor {
                  __typename
                  name
                  bioDescription
                  role
                  accolades {
                    figure
                    description
                  }
                  image
                }
              }
            }
          }
        }
      }
      ... on PagesPageLayersLayerSponsors {
        title
        sponsors {
          __typename
          name
          link
        }
      }
      ... on PagesPageLayersCuratedCollection {
        curatedDescription
        posts_collection {
          __typename
          reference {
            __typename
            ... on PostsDocument {
              data {
                ... on PostsPost {
                  title
                }
              }
            }
          }
        }
      }
      ... on PagesPageLayersLayerCta {
        ctaDescription
        cta_text
        cta_link
        cta_image
      }
    }
  }
  ... on PagesTrainingPage {
    faq {
      __typename
      question
      answer
    }
  }
}
