query getCuratedPostAndNavDocument($relativePath: String!) {
  getNavDocument(relativePath: "site-nav.md") {
    data {
      ...NavParts2
    }
  }
  getCuratedDocument(relativePath: $relativePath) {
    id
    sys {
      filename
    }
    data {
      __typename
      ... on CuratedCurated {
        title
        curations {
          __typename
          ... on CuratedCuratedCurationsCuratedHero {
            description
            hero_post {
              __typename
              ... on PostsDocument {
                sys {
                  filename
                  collection {
                    slug
                  }
                  breadcrumbs
                }
                data {
                  __typename
                  ... on PostsPost {
                    ...PostsParts
                    author {
                      __typename
                      ... on AuthorsDocument {
                        sys {
                          filename
                        }
                        data {
                          ... on AuthorsAuthor {
                            name
                            image
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
          ... on CuratedCuratedCurationsCuratedCollection {
            description
            posts_collection {
              __typename
              reference {
                __typename
                ... on PostsDocument {
                  id
                  sys {
                    filename
                    collection {
                      slug
                    }
                    breadcrumbs
                  }
                  data {
                    __typename
                    ... on PostsPost {
                      ...PostsParts
                      author {
                        __typename
                        ... on AuthorsDocument {
                          sys {
                            filename
                          }
                          data {
                            ... on AuthorsAuthor {
                              name
                              image
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

query getPostAndNav($relativePath: String!) {
  getNavDocument(relativePath: "site-nav.md") {
    data {
      ...NavParts2
    }
  }
  getPostsDocument(relativePath: $relativePath) {
    id
    sys {
      filename
      collection {
        slug
      }
    }
    data {
      ...PostsParts
      ... on PostsPost {
        author {
          ... on AuthorsDocument {
            id
            sys {
              filename
              collection {
                slug
              }
            }
            data {
              ... on AuthorsAuthor {
                ...AuthorsParts
              }
            }
          }
        }
      }
    }
  }
}
