// DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
  JSONObject: any;
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  sys?: Maybe<SystemInfo>;
  id: Scalars['ID'];
};

export type FormField = {
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};




export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename?: Maybe<Scalars['String']>;
  basename?: Maybe<Scalars['String']>;
  breadcrumbs?: Maybe<Array<Maybe<Scalars['String']>>>;
  path?: Maybe<Scalars['String']>;
  relativePath?: Maybe<Scalars['String']>;
  extension?: Maybe<Scalars['String']>;
  template?: Maybe<Scalars['String']>;
  collection?: Maybe<Section>;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars['Boolean']>;
};

export type Section = {
  __typename?: 'Section';
  type?: Maybe<Scalars['String']>;
  path?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  create?: Maybe<Scalars['String']>;
  match?: Maybe<Scalars['String']>;
  new_doc_ext?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['String']>>>;
  slug?: Maybe<Scalars['String']>;
  documents?: Maybe<Array<Maybe<Document>>>;
};

export type SectionDocumentUnion = Training_Document | Posts_Document | Pages_Document | Forms_Document | Curated_Document | Authors_Document | Nav_Document;

export type SectionParams = {
  training?: Maybe<Training_Input>;
  posts?: Maybe<Posts_Input>;
  pages?: Maybe<Pages_Input>;
  forms?: Maybe<Forms_Input>;
  curated?: Maybe<Curated_Input>;
  authors?: Maybe<Authors_Input>;
  nav?: Maybe<Nav_Input>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument?: Maybe<Document>;
  updateDocument?: Maybe<SectionDocumentUnion>;
  updateTrainingDocument?: Maybe<Training_Document>;
  updatePostsDocument?: Maybe<Posts_Document>;
  updatePagesDocument?: Maybe<Pages_Document>;
  updateFormsDocument?: Maybe<Forms_Document>;
  updateCuratedDocument?: Maybe<Curated_Document>;
  updateAuthorsDocument?: Maybe<Authors_Document>;
  updateNavDocument?: Maybe<Nav_Document>;
};


export type MutationAddPendingDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  collection?: Maybe<Scalars['String']>;
  template?: Maybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<SectionParams>;
};


export type MutationUpdateTrainingDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<Training_Input>;
};


export type MutationUpdatePostsDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<Posts_Input>;
};


export type MutationUpdatePagesDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<Pages_Input>;
};


export type MutationUpdateFormsDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<Forms_Input>;
};


export type MutationUpdateCuratedDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<Curated_Input>;
};


export type MutationUpdateAuthorsDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<Authors_Input>;
};


export type MutationUpdateNavDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
  params?: Maybe<Nav_Input>;
};

export type Query = {
  __typename?: 'Query';
  node?: Maybe<Node>;
  getDocument?: Maybe<SectionDocumentUnion>;
  getCollections?: Maybe<Array<Maybe<Section>>>;
  getCollection?: Maybe<Section>;
  getTrainingDocument?: Maybe<Training_Document>;
  getTrainingList?: Maybe<Array<Maybe<Training_Document>>>;
  getPostsDocument?: Maybe<Posts_Document>;
  getPostsList?: Maybe<Array<Maybe<Posts_Document>>>;
  getPagesDocument?: Maybe<Pages_Document>;
  getPagesList?: Maybe<Array<Maybe<Pages_Document>>>;
  getFormsDocument?: Maybe<Forms_Document>;
  getFormsList?: Maybe<Array<Maybe<Forms_Document>>>;
  getCuratedDocument?: Maybe<Curated_Document>;
  getCuratedList?: Maybe<Array<Maybe<Curated_Document>>>;
  getAuthorsDocument?: Maybe<Authors_Document>;
  getAuthorsList?: Maybe<Array<Maybe<Authors_Document>>>;
  getNavDocument?: Maybe<Nav_Document>;
  getNavList?: Maybe<Array<Maybe<Nav_Document>>>;
};


export type QueryNodeArgs = {
  id: Scalars['ID'];
};


export type QueryGetDocumentArgs = {
  collection?: Maybe<Scalars['String']>;
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetCollectionArgs = {
  collection?: Maybe<Scalars['String']>;
};


export type QueryGetTrainingDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetPostsDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetPagesDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetFormsDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetCuratedDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetAuthorsDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetNavDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};

export type Training_Data = Training_Doc_Data;

export type Training_Input = {
  training?: Maybe<Training_Doc_Input>;
};

export type Training_Values = Training_Doc_Values;

export type Training_Form = Training_Doc_Form;

export type Training_Document = Node & Document & {
  __typename?: 'Training_Document';
  id: Scalars['ID'];
  sys?: Maybe<SystemInfo>;
  data?: Maybe<Training_Data>;
  values?: Maybe<Training_Values>;
  form?: Maybe<Training_Form>;
};

export type Training_Workouts_Data = {
  __typename?: 'Training_Workouts_Data';
  Day?: Maybe<Scalars['Int']>;
  Title?: Maybe<Scalars['String']>;
  Description?: Maybe<Scalars['String']>;
  Category?: Maybe<Scalars['String']>;
};

export type Training_Doc_Data = {
  __typename?: 'Training_Doc_Data';
  name?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  event?: Maybe<Scalars['String']>;
  category?: Maybe<Scalars['String']>;
  time?: Maybe<Scalars['String']>;
  workouts?: Maybe<Array<Maybe<Training_Workouts_Data>>>;
  _body?: Maybe<Scalars['String']>;
};

export type Training_Workouts_Values = {
  __typename?: 'Training_Workouts_Values';
  Day?: Maybe<Scalars['Int']>;
  Title?: Maybe<Scalars['String']>;
  Description?: Maybe<Scalars['String']>;
  Category?: Maybe<Scalars['Reference']>;
};

export type Training_Doc_Values = {
  __typename?: 'Training_Doc_Values';
  name?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  event?: Maybe<Scalars['Reference']>;
  category?: Maybe<Scalars['Reference']>;
  time?: Maybe<Scalars['String']>;
  workouts?: Maybe<Array<Maybe<Training_Workouts_Values>>>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type TextField = FormField & {
  __typename?: 'TextField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type TextareaField = FormField & {
  __typename?: 'TextareaField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type SelectField = FormField & {
  __typename?: 'SelectField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type NumberField = FormField & {
  __typename?: 'NumberField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type Training_Workouts_FormFieldsUnion = NumberField | TextField | TextareaField | SelectField;

export type Training_Workouts_GroupListField = FormField & {
  __typename?: 'Training_Workouts_GroupListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Training_Workouts_FormFieldsUnion>>>;
};

export type Training_Doc_FormFieldsUnion = TextField | TextareaField | SelectField | Training_Workouts_GroupListField;

export type Training_Doc_Form = {
  __typename?: 'Training_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Training_Doc_FormFieldsUnion>>>;
};

export type Training_Workouts_Input = {
  Day?: Maybe<Scalars['Int']>;
  Title?: Maybe<Scalars['String']>;
  Description?: Maybe<Scalars['String']>;
  Category?: Maybe<Scalars['String']>;
};

export type Training_Doc_Input = {
  name?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  event?: Maybe<Scalars['String']>;
  category?: Maybe<Scalars['String']>;
  time?: Maybe<Scalars['String']>;
  workouts?: Maybe<Array<Maybe<Training_Workouts_Input>>>;
  _body?: Maybe<Scalars['String']>;
};

export type Posts_Data = Post_Doc_Data;

export type Posts_Input = {
  post?: Maybe<Post_Doc_Input>;
};

export type Posts_Values = Post_Doc_Values;

export type Posts_Form = Post_Doc_Form;

export type Posts_Document = Node & Document & {
  __typename?: 'Posts_Document';
  id: Scalars['ID'];
  sys?: Maybe<SystemInfo>;
  data?: Maybe<Posts_Data>;
  values?: Maybe<Posts_Values>;
  form?: Maybe<Posts_Form>;
};

export type Post_Accolades_Data = {
  __typename?: 'Post_Accolades_Data';
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type Post_Doc_Data = {
  __typename?: 'Post_Doc_Data';
  title?: Maybe<Scalars['String']>;
  tags?: Maybe<Array<Maybe<Scalars['String']>>>;
  image?: Maybe<Scalars['String']>;
  image_small?: Maybe<Scalars['String']>;
  accolades?: Maybe<Post_Accolades_Data>;
  author?: Maybe<Authors_Document>;
  preface?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['String']>;
};

export type Post_Accolades_Values = {
  __typename?: 'Post_Accolades_Values';
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type Post_Doc_Values = {
  __typename?: 'Post_Doc_Values';
  title?: Maybe<Scalars['String']>;
  tags?: Maybe<Array<Maybe<Scalars['String']>>>;
  image?: Maybe<Scalars['String']>;
  image_small?: Maybe<Scalars['String']>;
  accolades?: Maybe<Post_Accolades_Values>;
  author?: Maybe<Scalars['Reference']>;
  preface?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type TagListField = FormField & {
  __typename?: 'TagListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type Post_Accolades_FormFieldsUnion = TextField;

export type Post_Accolades_GroupField = FormField & {
  __typename?: 'Post_Accolades_GroupField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Post_Accolades_FormFieldsUnion>>>;
};

export type Post_Doc_FormFieldsUnion = TextField | TagListField | Post_Accolades_GroupField | SelectField | TextareaField;

export type Post_Doc_Form = {
  __typename?: 'Post_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Post_Doc_FormFieldsUnion>>>;
};

export type Post_Accolades_Input = {
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type Post_Doc_Input = {
  title?: Maybe<Scalars['String']>;
  tags?: Maybe<Array<Maybe<Scalars['String']>>>;
  image?: Maybe<Scalars['String']>;
  image_small?: Maybe<Scalars['String']>;
  accolades?: Maybe<Post_Accolades_Input>;
  author?: Maybe<Scalars['String']>;
  preface?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['String']>;
};

export type Pages_Data = Page_Doc_Data | TrainingPage_Doc_Data;

export type Pages_Input = {
  page?: Maybe<Page_Doc_Input>;
  trainingPage?: Maybe<TrainingPage_Doc_Input>;
};

export type Pages_Values = Page_Doc_Values | TrainingPage_Doc_Values;

export type Pages_Form = Page_Doc_Form | TrainingPage_Doc_Form;

export type Pages_Document = Node & Document & {
  __typename?: 'Pages_Document';
  id: Scalars['ID'];
  sys?: Maybe<SystemInfo>;
  data?: Maybe<Pages_Data>;
  values?: Maybe<Pages_Values>;
  form?: Maybe<Pages_Form>;
};

export type Page_Seo_Data = {
  __typename?: 'Page_Seo_Data';
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type LayerTeam_Data = {
  __typename?: 'LayerTeam_Data';
  description?: Maybe<Scalars['String']>;
  members?: Maybe<Array<Maybe<Authors_Document>>>;
};

export type LayerPostList_Data = {
  __typename?: 'LayerPostList_Data';
  description?: Maybe<Scalars['String']>;
  posts?: Maybe<Array<Maybe<Posts_Document>>>;
};

export type LayerDarkFeature_FeatureList_Data = {
  __typename?: 'LayerDarkFeature_FeatureList_Data';
  header?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type LayerDarkFeature_Data = {
  __typename?: 'LayerDarkFeature_Data';
  hint?: Maybe<Scalars['String']>;
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  feature_list?: Maybe<Array<Maybe<LayerDarkFeature_FeatureList_Data>>>;
};

export type LayerLeadership_Data = {
  __typename?: 'LayerLeadership_Data';
  title?: Maybe<Scalars['String']>;
  leaders?: Maybe<Array<Maybe<Authors_Document>>>;
};

export type LayerSponsors_Sponsors_Data = {
  __typename?: 'LayerSponsors_Sponsors_Data';
  name?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
};

export type LayerSponsors_Data = {
  __typename?: 'LayerSponsors_Data';
  title?: Maybe<Scalars['String']>;
  sponsors?: Maybe<Array<Maybe<LayerSponsors_Sponsors_Data>>>;
};

export type CuratedCollection_Data = {
  __typename?: 'CuratedCollection_Data';
  description?: Maybe<Scalars['String']>;
  posts_collection?: Maybe<Array<Maybe<Posts_Document>>>;
};

export type LayerCta_Data = {
  __typename?: 'LayerCta_Data';
  description?: Maybe<Scalars['String']>;
  cta_text?: Maybe<Scalars['String']>;
  cta_link?: Maybe<Scalars['String']>;
  cta_image?: Maybe<Scalars['String']>;
};

export type Page_Layers_Data = LayerTeam_Data | LayerPostList_Data | LayerDarkFeature_Data | LayerLeadership_Data | LayerSponsors_Data | CuratedCollection_Data | LayerCta_Data;

export type Page_Doc_Data = {
  __typename?: 'Page_Doc_Data';
  title?: Maybe<Scalars['String']>;
  seo?: Maybe<Page_Seo_Data>;
  layers?: Maybe<Array<Maybe<Page_Layers_Data>>>;
  _body?: Maybe<Scalars['String']>;
};

export type Page_Seo_Values = {
  __typename?: 'Page_Seo_Values';
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type LayerTeam_Values = {
  __typename?: 'LayerTeam_Values';
  description?: Maybe<Scalars['String']>;
  members?: Maybe<Array<Maybe<Scalars['String']>>>;
  _template?: Maybe<Scalars['String']>;
};

export type LayerPostList_Values = {
  __typename?: 'LayerPostList_Values';
  description?: Maybe<Scalars['String']>;
  posts?: Maybe<Array<Maybe<Scalars['String']>>>;
  _template?: Maybe<Scalars['String']>;
};

export type LayerDarkFeature_FeatureList_Values = {
  __typename?: 'LayerDarkFeature_FeatureList_Values';
  header?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type LayerDarkFeature_Values = {
  __typename?: 'LayerDarkFeature_Values';
  hint?: Maybe<Scalars['String']>;
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  feature_list?: Maybe<Array<Maybe<LayerDarkFeature_FeatureList_Values>>>;
  _template?: Maybe<Scalars['String']>;
};

export type LayerLeadership_Values = {
  __typename?: 'LayerLeadership_Values';
  title?: Maybe<Scalars['String']>;
  leaders?: Maybe<Array<Maybe<Scalars['String']>>>;
  _template?: Maybe<Scalars['String']>;
};

export type LayerSponsors_Sponsors_Values = {
  __typename?: 'LayerSponsors_Sponsors_Values';
  name?: Maybe<Scalars['Reference']>;
  link?: Maybe<Scalars['String']>;
};

export type LayerSponsors_Values = {
  __typename?: 'LayerSponsors_Values';
  title?: Maybe<Scalars['String']>;
  sponsors?: Maybe<Array<Maybe<LayerSponsors_Sponsors_Values>>>;
  _template?: Maybe<Scalars['String']>;
};

export type CuratedCollection_Values = {
  __typename?: 'CuratedCollection_Values';
  description?: Maybe<Scalars['String']>;
  posts_collection?: Maybe<Array<Maybe<Scalars['String']>>>;
  _template?: Maybe<Scalars['String']>;
};

export type LayerCta_Values = {
  __typename?: 'LayerCta_Values';
  description?: Maybe<Scalars['String']>;
  cta_text?: Maybe<Scalars['String']>;
  cta_link?: Maybe<Scalars['String']>;
  cta_image?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type Page_Layers_Values = LayerTeam_Values | LayerPostList_Values | LayerDarkFeature_Values | LayerLeadership_Values | LayerSponsors_Values | CuratedCollection_Values | LayerCta_Values;

export type Page_Doc_Values = {
  __typename?: 'Page_Doc_Values';
  title?: Maybe<Scalars['String']>;
  seo?: Maybe<Page_Seo_Values>;
  layers?: Maybe<Array<Maybe<Page_Layers_Values>>>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type Page_Seo_FormFieldsUnion = TextField;

export type Page_Seo_GroupField = FormField & {
  __typename?: 'Page_Seo_GroupField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Page_Seo_FormFieldsUnion>>>;
};

export type List_FormFieldsUnion = TextField | SelectField;

export type ListField = FormField & {
  __typename?: 'ListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  defaultItem?: Maybe<Scalars['String']>;
  field?: Maybe<List_FormFieldsUnion>;
};

export type LayerTeam_FormFieldsUnion = TextareaField | ListField;

export type LayerTeam_Form = {
  __typename?: 'LayerTeam_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<LayerTeam_FormFieldsUnion>>>;
};

export type LayerPostList_FormFieldsUnion = TextareaField | ListField;

export type LayerPostList_Form = {
  __typename?: 'LayerPostList_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<LayerPostList_FormFieldsUnion>>>;
};

export type LayerDarkFeature_FeatureList_FormFieldsUnion = TextField;

export type LayerDarkFeature_FeatureList_GroupListField = FormField & {
  __typename?: 'LayerDarkFeature_FeatureList_GroupListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<LayerDarkFeature_FeatureList_FormFieldsUnion>>>;
};

export type LayerDarkFeature_FormFieldsUnion = TextField | TextareaField | LayerDarkFeature_FeatureList_GroupListField;

export type LayerDarkFeature_Form = {
  __typename?: 'LayerDarkFeature_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<LayerDarkFeature_FormFieldsUnion>>>;
};

export type LayerLeadership_FormFieldsUnion = TextField | ListField;

export type LayerLeadership_Form = {
  __typename?: 'LayerLeadership_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<LayerLeadership_FormFieldsUnion>>>;
};

export type LayerSponsors_Sponsors_FormFieldsUnion = SelectField | TextField;

export type LayerSponsors_Sponsors_GroupListField = FormField & {
  __typename?: 'LayerSponsors_Sponsors_GroupListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<LayerSponsors_Sponsors_FormFieldsUnion>>>;
};

export type LayerSponsors_FormFieldsUnion = TextField | LayerSponsors_Sponsors_GroupListField;

export type LayerSponsors_Form = {
  __typename?: 'LayerSponsors_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<LayerSponsors_FormFieldsUnion>>>;
};

export type CuratedCollection_FormFieldsUnion = TextareaField | ListField;

export type CuratedCollection_Form = {
  __typename?: 'CuratedCollection_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<CuratedCollection_FormFieldsUnion>>>;
};

export type LayerCta_FormFieldsUnion = TextareaField | TextField;

export type LayerCta_Form = {
  __typename?: 'LayerCta_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<LayerCta_FormFieldsUnion>>>;
};

export type Page_Layers_BlocksFieldTemplates = {
  __typename?: 'Page_Layers_BlocksFieldTemplates';
  layerTeam?: Maybe<LayerTeam_Form>;
  layerPostList?: Maybe<LayerPostList_Form>;
  layerDarkFeature?: Maybe<LayerDarkFeature_Form>;
  layerLeadership?: Maybe<LayerLeadership_Form>;
  layerSponsors?: Maybe<LayerSponsors_Form>;
  curatedCollection?: Maybe<CuratedCollection_Form>;
  layerCta?: Maybe<LayerCta_Form>;
};

export type Page_Layers_BlocksField = FormField & {
  __typename?: 'Page_Layers_BlocksField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  templates?: Maybe<Page_Layers_BlocksFieldTemplates>;
};

export type Page_Doc_FormFieldsUnion = TextField | Page_Seo_GroupField | Page_Layers_BlocksField | TextareaField;

export type Page_Doc_Form = {
  __typename?: 'Page_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Page_Doc_FormFieldsUnion>>>;
};

export type Page_Seo_Input = {
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type LayerTeam_Input = {
  description?: Maybe<Scalars['String']>;
  members?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type LayerPostList_Input = {
  description?: Maybe<Scalars['String']>;
  posts?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type LayerDarkFeature_FeatureList_Input = {
  header?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type LayerDarkFeature_Input = {
  hint?: Maybe<Scalars['String']>;
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  feature_list?: Maybe<Array<Maybe<LayerDarkFeature_FeatureList_Input>>>;
};

export type LayerLeadership_Input = {
  title?: Maybe<Scalars['String']>;
  leaders?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type LayerSponsors_Sponsors_Input = {
  name?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
};

export type LayerSponsors_Input = {
  title?: Maybe<Scalars['String']>;
  sponsors?: Maybe<Array<Maybe<LayerSponsors_Sponsors_Input>>>;
};

export type CuratedCollection_Input = {
  description?: Maybe<Scalars['String']>;
  posts_collection?: Maybe<Array<Maybe<Scalars['String']>>>;
};

export type LayerCta_Input = {
  description?: Maybe<Scalars['String']>;
  cta_text?: Maybe<Scalars['String']>;
  cta_link?: Maybe<Scalars['String']>;
  cta_image?: Maybe<Scalars['String']>;
};

export type Layers_Input = {
  layerTeam?: Maybe<LayerTeam_Input>;
  layerPostList?: Maybe<LayerPostList_Input>;
  layerDarkFeature?: Maybe<LayerDarkFeature_Input>;
  layerLeadership?: Maybe<LayerLeadership_Input>;
  layerSponsors?: Maybe<LayerSponsors_Input>;
  curatedCollection?: Maybe<CuratedCollection_Input>;
  layerCta?: Maybe<LayerCta_Input>;
};

export type Page_Doc_Input = {
  title?: Maybe<Scalars['String']>;
  seo?: Maybe<Page_Seo_Input>;
  layers?: Maybe<Array<Maybe<Layers_Input>>>;
  _body?: Maybe<Scalars['String']>;
};

export type TrainingPage_Faq_Data = {
  __typename?: 'TrainingPage_Faq_Data';
  question?: Maybe<Scalars['String']>;
  answer?: Maybe<Scalars['String']>;
};

export type TrainingPage_Doc_Data = {
  __typename?: 'TrainingPage_Doc_Data';
  faq?: Maybe<Array<Maybe<TrainingPage_Faq_Data>>>;
  _body?: Maybe<Scalars['String']>;
};

export type TrainingPage_Faq_Values = {
  __typename?: 'TrainingPage_Faq_Values';
  question?: Maybe<Scalars['String']>;
  answer?: Maybe<Scalars['String']>;
};

export type TrainingPage_Doc_Values = {
  __typename?: 'TrainingPage_Doc_Values';
  faq?: Maybe<Array<Maybe<TrainingPage_Faq_Values>>>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type TrainingPage_Faq_FormFieldsUnion = TextField;

export type TrainingPage_Faq_GroupListField = FormField & {
  __typename?: 'TrainingPage_Faq_GroupListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<TrainingPage_Faq_FormFieldsUnion>>>;
};

export type TrainingPage_Doc_FormFieldsUnion = TrainingPage_Faq_GroupListField | TextareaField;

export type TrainingPage_Doc_Form = {
  __typename?: 'TrainingPage_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<TrainingPage_Doc_FormFieldsUnion>>>;
};

export type TrainingPage_Faq_Input = {
  question?: Maybe<Scalars['String']>;
  answer?: Maybe<Scalars['String']>;
};

export type TrainingPage_Doc_Input = {
  faq?: Maybe<Array<Maybe<TrainingPage_Faq_Input>>>;
  _body?: Maybe<Scalars['String']>;
};

export type Forms_Data = JenCcoaching_Doc_Data;

export type Forms_Input = {
  jenCcoaching?: Maybe<JenCcoaching_Doc_Input>;
};

export type Forms_Values = JenCcoaching_Doc_Values;

export type Forms_Form = JenCcoaching_Doc_Form;

export type Forms_Document = Node & Document & {
  __typename?: 'Forms_Document';
  id: Scalars['ID'];
  sys?: Maybe<SystemInfo>;
  data?: Maybe<Forms_Data>;
  values?: Maybe<Forms_Values>;
  form?: Maybe<Forms_Form>;
};

export type FieldBoolean_Data = {
  __typename?: 'FieldBoolean_Data';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
};

export type FieldText_Data = {
  __typename?: 'FieldText_Data';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  prefix?: Maybe<Scalars['String']>;
  suffix?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
};

export type FieldTextarea_Data = {
  __typename?: 'FieldTextarea_Data';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
};

export type FieldCheckbox_Options_Data = {
  __typename?: 'FieldCheckbox_Options_Data';
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
};

export type FieldCheckbox_Data = {
  __typename?: 'FieldCheckbox_Data';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<FieldCheckbox_Options_Data>>>;
};

export type FieldRadio_Options_Data = {
  __typename?: 'FieldRadio_Options_Data';
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
};

export type FieldRadio_Data = {
  __typename?: 'FieldRadio_Data';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<FieldRadio_Options_Data>>>;
};

export type FieldGroupText_Fields_Data = FieldText_Data;

export type FieldGroupText_Data = {
  __typename?: 'FieldGroupText_Data';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<FieldGroupText_Fields_Data>>>;
  prefix_class?: Maybe<Scalars['String']>;
};

export type FieldWeekCheckbox_Data = {
  __typename?: 'FieldWeekCheckbox_Data';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
};

export type JenCcoaching_Fields_Data = FieldBoolean_Data | FieldText_Data | FieldTextarea_Data | FieldCheckbox_Data | FieldRadio_Data | FieldGroupText_Data | FieldWeekCheckbox_Data;

export type JenCcoaching_Doc_Data = {
  __typename?: 'JenCcoaching_Doc_Data';
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<JenCcoaching_Fields_Data>>>;
  _body?: Maybe<Scalars['String']>;
};

export type FieldBoolean_Values = {
  __typename?: 'FieldBoolean_Values';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type FieldText_Values = {
  __typename?: 'FieldText_Values';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  prefix?: Maybe<Scalars['String']>;
  suffix?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type FieldTextarea_Values = {
  __typename?: 'FieldTextarea_Values';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type FieldCheckbox_Options_Values = {
  __typename?: 'FieldCheckbox_Options_Values';
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
};

export type FieldCheckbox_Values = {
  __typename?: 'FieldCheckbox_Values';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<FieldCheckbox_Options_Values>>>;
  _template?: Maybe<Scalars['String']>;
};

export type FieldRadio_Options_Values = {
  __typename?: 'FieldRadio_Options_Values';
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
};

export type FieldRadio_Values = {
  __typename?: 'FieldRadio_Values';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<FieldRadio_Options_Values>>>;
  _template?: Maybe<Scalars['String']>;
};

export type FieldGroupText_Fields_Values = FieldText_Values;

export type FieldGroupText_Values = {
  __typename?: 'FieldGroupText_Values';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<FieldGroupText_Fields_Values>>>;
  prefix_class?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type FieldWeekCheckbox_Values = {
  __typename?: 'FieldWeekCheckbox_Values';
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type JenCcoaching_Fields_Values = FieldBoolean_Values | FieldText_Values | FieldTextarea_Values | FieldCheckbox_Values | FieldRadio_Values | FieldGroupText_Values | FieldWeekCheckbox_Values;

export type JenCcoaching_Doc_Values = {
  __typename?: 'JenCcoaching_Doc_Values';
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<JenCcoaching_Fields_Values>>>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type FieldBoolean_FormFieldsUnion = TextField;

export type FieldBoolean_Form = {
  __typename?: 'FieldBoolean_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<FieldBoolean_FormFieldsUnion>>>;
};

export type FieldText_FormFieldsUnion = TextField;

export type FieldText_Form = {
  __typename?: 'FieldText_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<FieldText_FormFieldsUnion>>>;
};

export type FieldTextarea_FormFieldsUnion = TextField;

export type FieldTextarea_Form = {
  __typename?: 'FieldTextarea_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<FieldTextarea_FormFieldsUnion>>>;
};

export type FieldCheckbox_Options_FormFieldsUnion = TextField;

export type FieldCheckbox_Options_GroupListField = FormField & {
  __typename?: 'FieldCheckbox_Options_GroupListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<FieldCheckbox_Options_FormFieldsUnion>>>;
};

export type FieldCheckbox_FormFieldsUnion = TextField | FieldCheckbox_Options_GroupListField;

export type FieldCheckbox_Form = {
  __typename?: 'FieldCheckbox_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<FieldCheckbox_FormFieldsUnion>>>;
};

export type FieldRadio_Options_FormFieldsUnion = TextField;

export type FieldRadio_Options_GroupListField = FormField & {
  __typename?: 'FieldRadio_Options_GroupListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<FieldRadio_Options_FormFieldsUnion>>>;
};

export type FieldRadio_FormFieldsUnion = TextField | FieldRadio_Options_GroupListField;

export type FieldRadio_Form = {
  __typename?: 'FieldRadio_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<FieldRadio_FormFieldsUnion>>>;
};

export type FieldGroupText_Fields_BlocksFieldTemplates = {
  __typename?: 'FieldGroupText_Fields_BlocksFieldTemplates';
  fieldText?: Maybe<FieldText_Form>;
};

export type FieldGroupText_Fields_BlocksField = FormField & {
  __typename?: 'FieldGroupText_Fields_BlocksField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  templates?: Maybe<FieldGroupText_Fields_BlocksFieldTemplates>;
};

export type FieldGroupText_FormFieldsUnion = TextField | FieldGroupText_Fields_BlocksField;

export type FieldGroupText_Form = {
  __typename?: 'FieldGroupText_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<FieldGroupText_FormFieldsUnion>>>;
};

export type FieldWeekCheckbox_FormFieldsUnion = TextField;

export type FieldWeekCheckbox_Form = {
  __typename?: 'FieldWeekCheckbox_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<FieldWeekCheckbox_FormFieldsUnion>>>;
};

export type JenCcoaching_Fields_BlocksFieldTemplates = {
  __typename?: 'JenCcoaching_Fields_BlocksFieldTemplates';
  fieldBoolean?: Maybe<FieldBoolean_Form>;
  fieldText?: Maybe<FieldText_Form>;
  fieldTextarea?: Maybe<FieldTextarea_Form>;
  fieldCheckbox?: Maybe<FieldCheckbox_Form>;
  fieldRadio?: Maybe<FieldRadio_Form>;
  fieldGroupText?: Maybe<FieldGroupText_Form>;
  fieldWeekCheckbox?: Maybe<FieldWeekCheckbox_Form>;
};

export type JenCcoaching_Fields_BlocksField = FormField & {
  __typename?: 'JenCcoaching_Fields_BlocksField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  templates?: Maybe<JenCcoaching_Fields_BlocksFieldTemplates>;
};

export type JenCcoaching_Doc_FormFieldsUnion = TextField | TextareaField | JenCcoaching_Fields_BlocksField;

export type JenCcoaching_Doc_Form = {
  __typename?: 'JenCcoaching_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<JenCcoaching_Doc_FormFieldsUnion>>>;
};

export type FieldBoolean_Input = {
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
};

export type FieldText_Input = {
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  prefix?: Maybe<Scalars['String']>;
  suffix?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
};

export type FieldTextarea_Input = {
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
};

export type FieldCheckbox_Options_Input = {
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
};

export type FieldCheckbox_Input = {
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<FieldCheckbox_Options_Input>>>;
};

export type FieldRadio_Options_Input = {
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
};

export type FieldRadio_Input = {
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  options?: Maybe<Array<Maybe<FieldRadio_Options_Input>>>;
};

export type Fields_Input = {
  fieldText?: Maybe<FieldText_Input>;
};

export type FieldGroupText_Input = {
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Fields_Input>>>;
  prefix_class?: Maybe<Scalars['String']>;
};

export type FieldWeekCheckbox_Input = {
  label?: Maybe<Scalars['String']>;
  subLabel?: Maybe<Scalars['String']>;
  placeholder?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
};

export type JenCcoaching_Doc_Input = {
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Fields_Input>>>;
  _body?: Maybe<Scalars['String']>;
};

export type Curated_Data = Curated_Doc_Data;

export type Curated_Input = {
  curated?: Maybe<Curated_Doc_Input>;
};

export type Curated_Values = Curated_Doc_Values;

export type Curated_Form = Curated_Doc_Form;

export type Curated_Document = Node & Document & {
  __typename?: 'Curated_Document';
  id: Scalars['ID'];
  sys?: Maybe<SystemInfo>;
  data?: Maybe<Curated_Data>;
  values?: Maybe<Curated_Values>;
  form?: Maybe<Curated_Form>;
};

export type CuratedHero_Data = {
  __typename?: 'CuratedHero_Data';
  description?: Maybe<Scalars['String']>;
  hero_post?: Maybe<Posts_Document>;
};

export type Curated_Curations_Data = CuratedHero_Data | CuratedCollection_Data;

export type Curated_Doc_Data = {
  __typename?: 'Curated_Doc_Data';
  title?: Maybe<Scalars['String']>;
  curations?: Maybe<Array<Maybe<Curated_Curations_Data>>>;
  _body?: Maybe<Scalars['String']>;
};

export type CuratedHero_Values = {
  __typename?: 'CuratedHero_Values';
  description?: Maybe<Scalars['String']>;
  hero_post?: Maybe<Scalars['Reference']>;
  _template?: Maybe<Scalars['String']>;
};

export type Curated_Curations_Values = CuratedHero_Values | CuratedCollection_Values;

export type Curated_Doc_Values = {
  __typename?: 'Curated_Doc_Values';
  title?: Maybe<Scalars['String']>;
  curations?: Maybe<Array<Maybe<Curated_Curations_Values>>>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type CuratedHero_FormFieldsUnion = TextareaField | SelectField;

export type CuratedHero_Form = {
  __typename?: 'CuratedHero_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<CuratedHero_FormFieldsUnion>>>;
};

export type Curated_Curations_BlocksFieldTemplates = {
  __typename?: 'Curated_Curations_BlocksFieldTemplates';
  curatedHero?: Maybe<CuratedHero_Form>;
  curatedCollection?: Maybe<CuratedCollection_Form>;
};

export type Curated_Curations_BlocksField = FormField & {
  __typename?: 'Curated_Curations_BlocksField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  templates?: Maybe<Curated_Curations_BlocksFieldTemplates>;
};

export type Curated_Doc_FormFieldsUnion = TextField | Curated_Curations_BlocksField | TextareaField;

export type Curated_Doc_Form = {
  __typename?: 'Curated_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Curated_Doc_FormFieldsUnion>>>;
};

export type CuratedHero_Input = {
  description?: Maybe<Scalars['String']>;
  hero_post?: Maybe<Scalars['String']>;
};

export type Curations_Input = {
  curatedHero?: Maybe<CuratedHero_Input>;
  curatedCollection?: Maybe<CuratedCollection_Input>;
};

export type Curated_Doc_Input = {
  title?: Maybe<Scalars['String']>;
  curations?: Maybe<Array<Maybe<Curations_Input>>>;
  _body?: Maybe<Scalars['String']>;
};

export type Authors_Data = Author_Doc_Data | Athlete_Doc_Data;

export type Authors_Input = {
  author?: Maybe<Author_Doc_Input>;
  athlete?: Maybe<Athlete_Doc_Input>;
};

export type Authors_Values = Author_Doc_Values | Athlete_Doc_Values;

export type Authors_Form = Author_Doc_Form | Athlete_Doc_Form;

export type Authors_Document = Node & Document & {
  __typename?: 'Authors_Document';
  id: Scalars['ID'];
  sys?: Maybe<SystemInfo>;
  data?: Maybe<Authors_Data>;
  values?: Maybe<Authors_Values>;
  form?: Maybe<Authors_Form>;
};

export type Author_Accolades_Data = {
  __typename?: 'Author_Accolades_Data';
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type Author_Ebook_Data = {
  __typename?: 'Author_Ebook_Data';
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
  link_text?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type Author_Doc_Data = {
  __typename?: 'Author_Doc_Data';
  name?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  role?: Maybe<Scalars['String']>;
  accolades?: Maybe<Array<Maybe<Author_Accolades_Data>>>;
  image?: Maybe<Scalars['String']>;
  bio_image?: Maybe<Scalars['String']>;
  story_image?: Maybe<Scalars['String']>;
  form?: Maybe<Forms_Document>;
  posts_collection?: Maybe<Array<Maybe<Posts_Document>>>;
  ebook?: Maybe<Author_Ebook_Data>;
  _body?: Maybe<Scalars['String']>;
};

export type Author_Accolades_Values = {
  __typename?: 'Author_Accolades_Values';
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type Author_Ebook_Values = {
  __typename?: 'Author_Ebook_Values';
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
  link_text?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type Author_Doc_Values = {
  __typename?: 'Author_Doc_Values';
  name?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  role?: Maybe<Scalars['Reference']>;
  accolades?: Maybe<Array<Maybe<Author_Accolades_Values>>>;
  image?: Maybe<Scalars['String']>;
  bio_image?: Maybe<Scalars['String']>;
  story_image?: Maybe<Scalars['String']>;
  form?: Maybe<Scalars['Reference']>;
  posts_collection?: Maybe<Array<Maybe<Scalars['String']>>>;
  ebook?: Maybe<Author_Ebook_Values>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type Author_Accolades_FormFieldsUnion = TextField;

export type Author_Accolades_GroupListField = FormField & {
  __typename?: 'Author_Accolades_GroupListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Author_Accolades_FormFieldsUnion>>>;
};

export type Author_Ebook_FormFieldsUnion = TextField | TextareaField;

export type Author_Ebook_GroupField = FormField & {
  __typename?: 'Author_Ebook_GroupField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Author_Ebook_FormFieldsUnion>>>;
};

export type Author_Doc_FormFieldsUnion = TextField | TextareaField | SelectField | Author_Accolades_GroupListField | ListField | Author_Ebook_GroupField;

export type Author_Doc_Form = {
  __typename?: 'Author_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Author_Doc_FormFieldsUnion>>>;
};

export type Author_Accolades_Input = {
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type Author_Ebook_Input = {
  title?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
  link_text?: Maybe<Scalars['String']>;
  image?: Maybe<Scalars['String']>;
};

export type Author_Doc_Input = {
  name?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  role?: Maybe<Scalars['String']>;
  accolades?: Maybe<Array<Maybe<Author_Accolades_Input>>>;
  image?: Maybe<Scalars['String']>;
  bio_image?: Maybe<Scalars['String']>;
  story_image?: Maybe<Scalars['String']>;
  form?: Maybe<Scalars['String']>;
  posts_collection?: Maybe<Array<Maybe<Scalars['String']>>>;
  ebook?: Maybe<Author_Ebook_Input>;
  _body?: Maybe<Scalars['String']>;
};

export type Athlete_PersonalBests_Data = {
  __typename?: 'Athlete_PersonalBests_Data';
  event?: Maybe<Scalars['String']>;
  time?: Maybe<Scalars['String']>;
};

export type Athlete_Accolades_Data = {
  __typename?: 'Athlete_Accolades_Data';
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type Athlete_SocialMedia_Data = {
  __typename?: 'Athlete_SocialMedia_Data';
  source?: Maybe<Scalars['String']>;
  handle?: Maybe<Scalars['String']>;
};

export type Athlete_Doc_Data = {
  __typename?: 'Athlete_Doc_Data';
  name?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  country?: Maybe<Scalars['String']>;
  personal_bests?: Maybe<Array<Maybe<Athlete_PersonalBests_Data>>>;
  accolades?: Maybe<Array<Maybe<Athlete_Accolades_Data>>>;
  social_media?: Maybe<Array<Maybe<Athlete_SocialMedia_Data>>>;
  image?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['String']>;
};

export type Athlete_PersonalBests_Values = {
  __typename?: 'Athlete_PersonalBests_Values';
  event?: Maybe<Scalars['String']>;
  time?: Maybe<Scalars['String']>;
};

export type Athlete_Accolades_Values = {
  __typename?: 'Athlete_Accolades_Values';
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type Athlete_SocialMedia_Values = {
  __typename?: 'Athlete_SocialMedia_Values';
  source?: Maybe<Scalars['Reference']>;
  handle?: Maybe<Scalars['String']>;
};

export type Athlete_Doc_Values = {
  __typename?: 'Athlete_Doc_Values';
  name?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  country?: Maybe<Scalars['String']>;
  personal_bests?: Maybe<Array<Maybe<Athlete_PersonalBests_Values>>>;
  accolades?: Maybe<Array<Maybe<Athlete_Accolades_Values>>>;
  social_media?: Maybe<Array<Maybe<Athlete_SocialMedia_Values>>>;
  image?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type Athlete_PersonalBests_FormFieldsUnion = TextField;

export type Athlete_PersonalBests_GroupListField = FormField & {
  __typename?: 'Athlete_PersonalBests_GroupListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Athlete_PersonalBests_FormFieldsUnion>>>;
};

export type Athlete_Accolades_FormFieldsUnion = TextField;

export type Athlete_Accolades_GroupListField = FormField & {
  __typename?: 'Athlete_Accolades_GroupListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Athlete_Accolades_FormFieldsUnion>>>;
};

export type Athlete_SocialMedia_FormFieldsUnion = SelectField | TextField;

export type Athlete_SocialMedia_GroupListField = FormField & {
  __typename?: 'Athlete_SocialMedia_GroupListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Athlete_SocialMedia_FormFieldsUnion>>>;
};

export type Athlete_Doc_FormFieldsUnion = TextField | TextareaField | Athlete_PersonalBests_GroupListField | Athlete_Accolades_GroupListField | Athlete_SocialMedia_GroupListField;

export type Athlete_Doc_Form = {
  __typename?: 'Athlete_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Athlete_Doc_FormFieldsUnion>>>;
};

export type Athlete_PersonalBests_Input = {
  event?: Maybe<Scalars['String']>;
  time?: Maybe<Scalars['String']>;
};

export type Athlete_Accolades_Input = {
  figure?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
};

export type Athlete_SocialMedia_Input = {
  source?: Maybe<Scalars['String']>;
  handle?: Maybe<Scalars['String']>;
};

export type Athlete_Doc_Input = {
  name?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  country?: Maybe<Scalars['String']>;
  personal_bests?: Maybe<Array<Maybe<Athlete_PersonalBests_Input>>>;
  accolades?: Maybe<Array<Maybe<Athlete_Accolades_Input>>>;
  social_media?: Maybe<Array<Maybe<Athlete_SocialMedia_Input>>>;
  image?: Maybe<Scalars['String']>;
  _body?: Maybe<Scalars['String']>;
};

export type Nav_Data = Nav_Doc_Data;

export type Nav_Input = {
  nav?: Maybe<Nav_Doc_Input>;
};

export type Nav_Values = Nav_Doc_Values;

export type Nav_Form = Nav_Doc_Form;

export type Nav_Document = Node & Document & {
  __typename?: 'Nav_Document';
  id: Scalars['ID'];
  sys?: Maybe<SystemInfo>;
  data?: Maybe<Nav_Data>;
  values?: Maybe<Nav_Values>;
  form?: Maybe<Nav_Form>;
};

export type NavItemPopout_Children_Data = {
  __typename?: 'NavItemPopout_Children_Data';
  label?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  icon?: Maybe<Scalars['String']>;
};

export type NavItemPopout_Extra_Data = {
  __typename?: 'NavItemPopout_Extra_Data';
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  icon?: Maybe<Scalars['String']>;
};

export type NavItemPopout_Data = {
  __typename?: 'NavItemPopout_Data';
  label?: Maybe<Scalars['String']>;
  children?: Maybe<Array<Maybe<NavItemPopout_Children_Data>>>;
  extra?: Maybe<Array<Maybe<NavItemPopout_Extra_Data>>>;
};

export type NavItemMore_ReadMore_Data = {
  __typename?: 'NavItemMore_ReadMore_Data';
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
};

export type NavItemMore_Data = {
  __typename?: 'NavItemMore_Data';
  label?: Maybe<Scalars['String']>;
  featured_post?: Maybe<Posts_Document>;
  from_the_blog?: Maybe<Array<Maybe<Posts_Document>>>;
  read_more?: Maybe<NavItemMore_ReadMore_Data>;
};

export type NavItemLink_Data = {
  __typename?: 'NavItemLink_Data';
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
};

export type Nav_Items_Data = NavItemPopout_Data | NavItemMore_Data | NavItemLink_Data;

export type Nav_Doc_Data = {
  __typename?: 'Nav_Doc_Data';
  items?: Maybe<Array<Maybe<Nav_Items_Data>>>;
  show_auth?: Maybe<Scalars['Boolean']>;
  _body?: Maybe<Scalars['String']>;
};

export type NavItemPopout_Children_Values = {
  __typename?: 'NavItemPopout_Children_Values';
  label?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  icon?: Maybe<Scalars['String']>;
};

export type NavItemPopout_Extra_Values = {
  __typename?: 'NavItemPopout_Extra_Values';
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  icon?: Maybe<Scalars['String']>;
};

export type NavItemPopout_Values = {
  __typename?: 'NavItemPopout_Values';
  label?: Maybe<Scalars['String']>;
  children?: Maybe<Array<Maybe<NavItemPopout_Children_Values>>>;
  extra?: Maybe<Array<Maybe<NavItemPopout_Extra_Values>>>;
  _template?: Maybe<Scalars['String']>;
};

export type NavItemMore_ReadMore_Values = {
  __typename?: 'NavItemMore_ReadMore_Values';
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
};

export type NavItemMore_Values = {
  __typename?: 'NavItemMore_Values';
  label?: Maybe<Scalars['String']>;
  featured_post?: Maybe<Scalars['Reference']>;
  from_the_blog?: Maybe<Array<Maybe<Scalars['String']>>>;
  read_more?: Maybe<NavItemMore_ReadMore_Values>;
  _template?: Maybe<Scalars['String']>;
};

export type NavItemLink_Values = {
  __typename?: 'NavItemLink_Values';
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type Nav_Items_Values = NavItemPopout_Values | NavItemMore_Values | NavItemLink_Values;

export type Nav_Doc_Values = {
  __typename?: 'Nav_Doc_Values';
  items?: Maybe<Array<Maybe<Nav_Items_Values>>>;
  show_auth?: Maybe<Scalars['Boolean']>;
  _body?: Maybe<Scalars['String']>;
  _template?: Maybe<Scalars['String']>;
};

export type NavItemPopout_Children_FormFieldsUnion = TextField;

export type NavItemPopout_Children_GroupListField = FormField & {
  __typename?: 'NavItemPopout_Children_GroupListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<NavItemPopout_Children_FormFieldsUnion>>>;
};

export type NavItemPopout_Extra_FormFieldsUnion = TextField;

export type NavItemPopout_Extra_GroupListField = FormField & {
  __typename?: 'NavItemPopout_Extra_GroupListField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<NavItemPopout_Extra_FormFieldsUnion>>>;
};

export type NavItemPopout_FormFieldsUnion = TextField | NavItemPopout_Children_GroupListField | NavItemPopout_Extra_GroupListField;

export type NavItemPopout_Form = {
  __typename?: 'NavItemPopout_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<NavItemPopout_FormFieldsUnion>>>;
};

export type NavItemMore_ReadMore_FormFieldsUnion = TextField;

export type NavItemMore_ReadMore_GroupField = FormField & {
  __typename?: 'NavItemMore_ReadMore_GroupField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<NavItemMore_ReadMore_FormFieldsUnion>>>;
};

export type NavItemMore_FormFieldsUnion = TextField | SelectField | ListField | NavItemMore_ReadMore_GroupField;

export type NavItemMore_Form = {
  __typename?: 'NavItemMore_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<NavItemMore_FormFieldsUnion>>>;
};

export type NavItemLink_FormFieldsUnion = TextField;

export type NavItemLink_Form = {
  __typename?: 'NavItemLink_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<NavItemLink_FormFieldsUnion>>>;
};

export type Nav_Items_BlocksFieldTemplates = {
  __typename?: 'Nav_Items_BlocksFieldTemplates';
  navItemPopout?: Maybe<NavItemPopout_Form>;
  navItemMore?: Maybe<NavItemMore_Form>;
  navItemLink?: Maybe<NavItemLink_Form>;
};

export type Nav_Items_BlocksField = FormField & {
  __typename?: 'Nav_Items_BlocksField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
  templates?: Maybe<Nav_Items_BlocksFieldTemplates>;
};

export type BooleanField = FormField & {
  __typename?: 'BooleanField';
  name?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
  component?: Maybe<Scalars['String']>;
};

export type Nav_Doc_FormFieldsUnion = Nav_Items_BlocksField | BooleanField | TextareaField;

export type Nav_Doc_Form = {
  __typename?: 'Nav_Doc_Form';
  label?: Maybe<Scalars['String']>;
  name?: Maybe<Scalars['String']>;
  fields?: Maybe<Array<Maybe<Nav_Doc_FormFieldsUnion>>>;
};

export type NavItemPopout_Children_Input = {
  label?: Maybe<Scalars['String']>;
  description?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  icon?: Maybe<Scalars['String']>;
};

export type NavItemPopout_Extra_Input = {
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
  icon?: Maybe<Scalars['String']>;
};

export type NavItemPopout_Input = {
  label?: Maybe<Scalars['String']>;
  children?: Maybe<Array<Maybe<NavItemPopout_Children_Input>>>;
  extra?: Maybe<Array<Maybe<NavItemPopout_Extra_Input>>>;
};

export type NavItemMore_ReadMore_Input = {
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
};

export type NavItemMore_Input = {
  label?: Maybe<Scalars['String']>;
  featured_post?: Maybe<Scalars['String']>;
  from_the_blog?: Maybe<Array<Maybe<Scalars['String']>>>;
  read_more?: Maybe<NavItemMore_ReadMore_Input>;
};

export type NavItemLink_Input = {
  label?: Maybe<Scalars['String']>;
  value?: Maybe<Scalars['String']>;
};

export type Items_Input = {
  navItemPopout?: Maybe<NavItemPopout_Input>;
  navItemMore?: Maybe<NavItemMore_Input>;
  navItemLink?: Maybe<NavItemLink_Input>;
};

export type Nav_Doc_Input = {
  items?: Maybe<Array<Maybe<Items_Input>>>;
  show_auth?: Maybe<Scalars['Boolean']>;
  _body?: Maybe<Scalars['String']>;
};

