---
name: author
label: Author
fields:
  - name: name
    label: Name
    type: text
    description: Your first name & last name
  - name: description
    label: Description
    type: textarea
    description: Your first name & last name
  - name: role
    label: role
    type: select
    config:
      source:
        type: simple
      options:
        - Head Coach & Founder
        - Wellness Coach & Founder
        - Athlete
  - name: accolades
    type: field_group_list
    fields:
      - name: figure
        type: text
        label: Figure
        description: A single number or word to emphasize
      - name: description
        type: text
        label: Description
    label: Accolades
    description: Key accomplishments which make this person stand out
  - name: image
    label: Image URL
    type: text
    description: The external image URL
  - name: bio_image
    label: Bio Image URL
    type: text
    description: The external image URL
  - name: story_image
    label: Story Image URL
    type: text
    description: The external image URL
  - name: form
    label: Form
    type: select
    config:
      source:
        type: pages
        section: forms
  - name: posts_collection
    label: Post Collection
    type: list
    config:
      source:
        type: pages
        section: posts
  - name: ebook
    label: Ebook
    type: field_group
    fields:
      - name: title
        label: Title
        type: text
      - name: description
        label: Description
        type: textarea
      - name: link
        label: Link
        type: text
      - name: link_text
        label: Link text
        type: text
      - name: image
        label: Image
        type: text
