---
name: curated
label: Curated
fields:
  - type: text
    name: title
    label: Title
  - name: curations
    label: Curations
    type: blocks
    template_types:
      - curated-hero
      - curated-collection
