---
name: curatedHero
label: Curated Hero
fields:
  - label: Description
    name: description
    type: textarea
  - name: hero_post
    label: Hero Post
    type: select
    config:
      source:
        type: pages
        section: posts
