---
name: layer-post-list
label: Post List Layer
fields:
  - label: Description
    name: description
    type: textarea
  - name: posts
    label: Posts
    type: list
    config:
      source:
        type: pages
        section: posts
