---
name: layer-dark-feature
label: Post List Layer
fields:
  - label: Hint
    name: hint
    type: text
  - label: Title
    name: title
    type: text
  - label: Description
    name: description
    type: textarea
  - name: feature_list
    label: Feature List
    type: field_group_list
    fields:
      - name: header
        label: Header
        type: text
      - name: description
        type: text
        label: Description
