---
name: layerSponsors
label: Post List Layer
fields:
  - label: Title
    name: title
    type: text
  - label: Sponsors List
    name: sponsors
    type: field_group_list
    fields:
      - name: name
        label: Name
        type: select
        config:
          source:
            type: simple
          options:
            - kinetik
            - adidas
            - hyperice
      - name: link
        label: Link
        type: text
