---
label: Site Nav
name: nav
fields:
  - name: items
    label: Items
    type: blocks
    template_types:
      - navItemPopout
      - navItemMore
      - navItemLink
  - label: Show Auth
    name: show_auth
    type: boolean
