---
label: Nav Item More
name: navItemMore
fields:
  - label: Label
    name: label
    type: text
  - name: featured_post
    label: Featured Post
    type: select
    config:
      source:
        type: pages
        section: posts
  - name: from_the_blog
    label: From The Blog
    type: list
    config:
      source:
        type: pages
        section: posts
  - label: Read More
    name: read_more
    type: field_group
    fields:
      - type: text
        name: label
        label: Label
      - type: text
        name: value
        label: Value
