---
label: Nav Item Link
name: navItemLink
fields:
  - name: label
    label: Label
    type: text
  - name: value
    description: >-
      A URL-friendly version, ensure no spaces or special characters are
      included.
    label: Value
    type: text
