---
name: navItemPopout
label: Nav Item Popout
fields:
  - label: Label
    name: label
    type: text
  - label: Children
    name: children
    type: field_group_list
    fields:
      - type: text
        name: label
        label: Label
      - type: text
        name: description
        label: Description
      - type: text
        name: value
        label: Value
      - type: text
        name: icon
        label: Icon
  - label: Extra
    name: extra
    type: field_group_list
    fields:
      - type: text
        name: label
        label: Label
      - type: text
        name: value
        label: Value
      - type: text
        name: icon
        label: Icon
