---
name: page
label: Page
fields:
  - type: text
    name: title
    label: Title
  - type: field_group
    name: seo
    label: SEO
    fields:
      - type: text
        name: title
        label: Title
      - type: text
        name: description
        label: Description
      - type: text
        name: image
        label: Image
  - name: layers
    label: Layers
    type: blocks
    template_types:
      - layerTeam
      - layerPostList
      - layerDarkFeature
      - layerLeadership
      - layerSponsors
      - curatedCollection
      - layerCta
