query getPagesAndNavDocument($relativePath: String!) {
  nav(relativePath: "site-nav.md") {
    ...NavParts2
  }
  pages(relativePath: $relativePath) {
    ... on Document {
      id
    }
    __typename
    ...PagesPartsWithReferences
  }
}

fragment NavParts2 on Nav {
  ... on NavNav {
    items {
      __typename
      ... on NavNavItemsNavItemPopout {
        label
        children {
          __typename
          label
          description
          value
          icon
        }
        extra {
          __typename
          label
          value
          icon
        }
      }
      ... on NavNavItemsNavItemMore {
        label
        featured_post {
          ... on Document {
            id
            _sys {
              filename
              breadcrumbs
            }
          }
          ... on PostsPost {
            ... on PostsPost {
              image
              title
              preface
              author {
                ... on Document {
                  _sys {
                    filename
                  }
                }
                __typename
                ... on AuthorsAuthor {
                  __typename
                  ... on AuthorsAuthor {
                    name
                    image
                  }
                }
              }
            }
          }
        }
        from_the_blog {
          __typename
          reference {
            ... on Document {
              id
              _sys {
                filename
                breadcrumbs
              }
            }
            ... on PostsPost {
              ... on PostsPost {
                image
                title
                preface
                author {
                  ... on Document {
                    _sys {
                      filename
                    }
                  }
                  __typename
                  ... on AuthorsAuthor {
                    __typename
                    ... on AuthorsAuthor {
                      name
                      image
                    }
                  }
                }
              }
            }
          }
        }
        read_more {
          __typename
          label
          value
        }
      }
      ... on NavNavItemsNavItemLink {
        label
        value
      }
    }
    show_auth
  }
}

fragment PagesPartsWithReferences on Pages {
  ... on PagesPage {
    title
    seo {
      __typename
      title
      description
      image
    }
    layers {
      __typename
      ... on PagesPageLayersLayerHero {
        image
      }
      ... on PagesPageLayersLayerTeam {
        description
        members {
          __typename
          reference {
            __typename
            ... on AuthorsAthlete {
              name
              image
              country
              personal_bests {
                event
                time
              }
              social_media {
                source
                handle
              }
            }
            ... on AuthorsAuthor {
              __typename
              id
              _sys {
                filename
              }
              __typename
              ... on AuthorsAuthor {
                image
                name
                role
                bioDescription
              }
            }
            ... on Document {
              id
            }
          }
        }
      }
      ... on PagesPageLayersLayerPostList {
        postListDescription
        posts {
          __typename
          reference {
            ... on PostsPost {
              __typename
              _sys {
                filename
              }
              ... on PostsPost {
                ...PostsParts
              }
            }
          }
        }
      }
      ... on PagesPageLayersLayerLeadership {
        title
        leaders {
          __typename
          reference {
            ... on AuthorsAuthor {
              __typename
              _sys {
                filename
              }
              __typename
              name
              bioDescription
              role
              accolades {
                figure
                description
              }
              image
            }
          }
        }
      }
      ... on PagesPageLayersLayerSponsors {
        title
        sponsors {
          __typename
          name
          link
        }
      }
      ... on PagesPageLayersCuratedCollection {
        curatedDescription
        posts_collection {
          __typename
          reference {
            __typename
            ... on PostsPost {
              ... on PostsPost {
                title
              }
            }
          }
        }
      }
      ... on PagesPageLayersLayerCta {
        ctaDescription
        cta_text
        cta_link
        cta_image
      }
    }
  }
  ... on PagesTrainingPage {
    faq {
      __typename
      question
      answer
    }
  }
}
